// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKq_mbp45H2zR1Jz60ht6dQv2gh-n8MRs',
    appId: '1:977559727849:web:1ab7855e820396132eca78',
    messagingSenderId: '977559727849',
    projectId: 'fcm-notification-app-9789d',
    authDomain: 'fcm-notification-app-9789d.firebaseapp.com',
    storageBucket: 'fcm-notification-app-9789d.firebasestorage.app',
    measurementId: 'G-CPJ09ZQG05',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnmxmFcTQDAtxljpSIsNaTgFQKNTlOP7w',
    appId: '1:977559727849:android:da644824adf5cc4b2eca78',
    messagingSenderId: '977559727849',
    projectId: 'fcm-notification-app-9789d',
    storageBucket: 'fcm-notification-app-9789d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiPrmLmPM-Ci4m2Vj3IMMG2Mc_w6eZg0o',
    appId: '1:977559727849:ios:0645f6f4d65f83ff2eca78',
    messagingSenderId: '977559727849',
    projectId: 'fcm-notification-app-9789d',
    storageBucket: 'fcm-notification-app-9789d.firebasestorage.app',
    iosBundleId: 'com.example.fcmNotificationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiPrmLmPM-Ci4m2Vj3IMMG2Mc_w6eZg0o',
    appId: '1:977559727849:ios:0645f6f4d65f83ff2eca78',
    messagingSenderId: '977559727849',
    projectId: 'fcm-notification-app-9789d',
    storageBucket: 'fcm-notification-app-9789d.firebasestorage.app',
    iosBundleId: 'com.example.fcmNotificationApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKq_mbp45H2zR1Jz60ht6dQv2gh-n8MRs',
    appId: '1:977559727849:web:3cb4fae68f1c2dc92eca78',
    messagingSenderId: '977559727849',
    projectId: 'fcm-notification-app-9789d',
    authDomain: 'fcm-notification-app-9789d.firebaseapp.com',
    storageBucket: 'fcm-notification-app-9789d.firebasestorage.app',
    measurementId: 'G-8X9MHM2PC6',
  );
}
