// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJJh_TF2ilInxEc95rIxRmTbWCu9SYbSY',
    appId: '1:405791121914:web:eda65ac23ed382ce9c0443',
    messagingSenderId: '405791121914',
    projectId: 'offline-first-chat-bloc-mvvm',
    authDomain: 'offline-first-chat-bloc-mvvm.firebaseapp.com',
    storageBucket: 'offline-first-chat-bloc-mvvm.firebasestorage.app',
    measurementId: 'G-6718HWX8R6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHDDpnDweFEnonCiY9TFBsUraNszejcbM',
    appId: '1:405791121914:android:5f13c267f1ab17ec9c0443',
    messagingSenderId: '405791121914',
    projectId: 'offline-first-chat-bloc-mvvm',
    storageBucket: 'offline-first-chat-bloc-mvvm.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFBBA77C65ZDJ9odjRZUHJ_6pW3Z1fqVU',
    appId: '1:405791121914:ios:cec86aa3128681459c0443',
    messagingSenderId: '405791121914',
    projectId: 'offline-first-chat-bloc-mvvm',
    storageBucket: 'offline-first-chat-bloc-mvvm.firebasestorage.app',
    iosBundleId: 'com.example.offlineFirstChatBlocMvvm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFBBA77C65ZDJ9odjRZUHJ_6pW3Z1fqVU',
    appId: '1:405791121914:ios:cec86aa3128681459c0443',
    messagingSenderId: '405791121914',
    projectId: 'offline-first-chat-bloc-mvvm',
    storageBucket: 'offline-first-chat-bloc-mvvm.firebasestorage.app',
    iosBundleId: 'com.example.offlineFirstChatBlocMvvm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJJh_TF2ilInxEc95rIxRmTbWCu9SYbSY',
    appId: '1:405791121914:web:1b3580a38c68cbb09c0443',
    messagingSenderId: '405791121914',
    projectId: 'offline-first-chat-bloc-mvvm',
    authDomain: 'offline-first-chat-bloc-mvvm.firebaseapp.com',
    storageBucket: 'offline-first-chat-bloc-mvvm.firebasestorage.app',
    measurementId: 'G-BSLJJLJ9E7',
  );
}
