// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJvOrXChDqYDfAomyVwdjDmtigsHJfZbU',
    appId: '1:896117374769:web:82373f018fdb57a1ae3a10',
    messagingSenderId: '896117374769',
    projectId: 'auth-project-fc856',
    authDomain: 'auth-project-fc856.firebaseapp.com',
    storageBucket: 'auth-project-fc856.firebasestorage.app',
    measurementId: 'G-116SG06M5T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9cnkV-9S0fwPwJaUtuKvCAh3_2RTDH94',
    appId: '1:896117374769:android:a6f214d1a3bbdc9fae3a10',
    messagingSenderId: '896117374769',
    projectId: 'auth-project-fc856',
    storageBucket: 'auth-project-fc856.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8UMCnpwBH0QV8NXx4WZ5pDXtQhpcwUBc',
    appId: '1:896117374769:ios:fa8dc66569118827ae3a10',
    messagingSenderId: '896117374769',
    projectId: 'auth-project-fc856',
    storageBucket: 'auth-project-fc856.firebasestorage.app',
    iosBundleId: 'com.example.firebaseFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8UMCnpwBH0QV8NXx4WZ5pDXtQhpcwUBc',
    appId: '1:896117374769:ios:fa8dc66569118827ae3a10',
    messagingSenderId: '896117374769',
    projectId: 'auth-project-fc856',
    storageBucket: 'auth-project-fc856.firebasestorage.app',
    iosBundleId: 'com.example.firebaseFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJvOrXChDqYDfAomyVwdjDmtigsHJfZbU',
    appId: '1:896117374769:web:bab92f4a685e9d78ae3a10',
    messagingSenderId: '896117374769',
    projectId: 'auth-project-fc856',
    authDomain: 'auth-project-fc856.firebaseapp.com',
    storageBucket: 'auth-project-fc856.firebasestorage.app',
    measurementId: 'G-TX1XMJXEZL',
  );
}
